### ISSUE TITLE
[Android] Issue with writing user redirect link data to a local file... EACCESS (Permission denied)

### ISSUE THREAD

**Issue by mrvivacious** [mrvivacious/PorNo-_Porn_Blocker#70]
wtf and why

Utilities.java:103 and 166 throw this exception:

```
W/System.err: 
  java.io.FileNotFoundException: /storage/emulated/0/PorNo_user_data/links.txt: open failed: EACCES (Permission denied)
W/System.err:    
  at libcore.io.IoBridge.open(IoBridge.java:496)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
    at us.mrvivacio.porno.Utilities.updateFile(Utilities.java:166)
    at us.mrvivacio.porno.MainActivity.onAddItemButtonPress(MainActivity.java:402)
```

**Comment by mrvivacious** [comment]
Fixed... I think. Made below edits and we can interact with storage as usual.

Changes: 
Upgraded `'com.google.firebase:firebase-firestore:17.1.5'` to `23.0.1`. Sync gradle.
